/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import DAOsImpl.AlunoDaoImpl;
import POJOs.Aluno;
import javax.swing.JOptionPane;

/**
 *
 * @author john
 */
public class FormAluno extends javax.swing.JDialog {

    /**
     * Creates new form FormAluno
     */
    public FormAluno(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField3 = new javax.swing.JTextField();
        janelaAluno = new javax.swing.JPanel();
        botaoVoltar = new javax.swing.JButton();
        abaAluno = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        labelNomeAluno = new javax.swing.JLabel();
        labelCpfAluno = new javax.swing.JLabel();
        campoNomeAluno = new javax.swing.JTextField();
        campoCpfAluno = new javax.swing.JTextField();
        ButtonSalvarInserirAluno = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblObjetos = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        labelCPFAluno = new javax.swing.JLabel();
        campoEditarCpfAluno = new javax.swing.JTextField();
        labelNomeAlunoN = new javax.swing.JLabel();
        campoNomeAlunoN = new javax.swing.JTextField();
        ButtonSalvarEditarAluno = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        labelRemoverCpfAluno = new javax.swing.JLabel();
        CampoRemoverCpfAluno = new javax.swing.JTextField();
        ButtonSalvarRemoverAluno = new javax.swing.JButton();

        jTextField3.setText("jTextField3");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        janelaAluno.setBorder(javax.swing.BorderFactory.createTitledBorder("Aluno"));
        janelaAluno.setToolTipText("");

        botaoVoltar.setText("Voltar");
        botaoVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVoltarActionPerformed(evt);
            }
        });

        labelNomeAluno.setText("Nome do Aluno: ");

        labelCpfAluno.setText("CPF do Aluno:");

        ButtonSalvarInserirAluno.setText("Salvar");
        ButtonSalvarInserirAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSalvarInserirAlunoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelCpfAluno)
                    .addComponent(labelNomeAluno))
                .addGap(4, 4, 4)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(campoCpfAluno, javax.swing.GroupLayout.DEFAULT_SIZE, 332, Short.MAX_VALUE)
                    .addComponent(campoNomeAluno))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(ButtonSalvarInserirAluno))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNomeAluno)
                    .addComponent(campoNomeAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCpfAluno)
                    .addComponent(campoCpfAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addComponent(ButtonSalvarInserirAluno))
        );

        abaAluno.addTab("Inserir", jPanel2);

        tblObjetos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblObjetos);

        abaAluno.addTab("Listar", jScrollPane1);

        labelCPFAluno.setText("CPF do Aluno:");

        labelNomeAlunoN.setText("Novo Nome:");

        ButtonSalvarEditarAluno.setText("Salvar");
        ButtonSalvarEditarAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSalvarEditarAlunoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelCPFAluno)
                    .addComponent(labelNomeAlunoN))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(campoEditarCpfAluno)
                    .addComponent(campoNomeAlunoN, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(ButtonSalvarEditarAluno))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCPFAluno)
                    .addComponent(campoEditarCpfAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNomeAlunoN)
                    .addComponent(campoNomeAlunoN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addComponent(ButtonSalvarEditarAluno))
        );

        abaAluno.addTab("Editar", jPanel3);

        labelRemoverCpfAluno.setText("CPF do Aluno:");

        ButtonSalvarRemoverAluno.setText("Salvar");
        ButtonSalvarRemoverAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSalvarRemoverAlunoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelRemoverCpfAluno)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CampoRemoverCpfAluno, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(ButtonSalvarRemoverAluno))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelRemoverCpfAluno)
                    .addComponent(CampoRemoverCpfAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 114, Short.MAX_VALUE)
                .addComponent(ButtonSalvarRemoverAluno))
        );

        abaAluno.addTab("Remover", jPanel4);

        javax.swing.GroupLayout janelaAlunoLayout = new javax.swing.GroupLayout(janelaAluno);
        janelaAluno.setLayout(janelaAlunoLayout);
        janelaAlunoLayout.setHorizontalGroup(
            janelaAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, janelaAlunoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(botaoVoltar))
            .addGroup(janelaAlunoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(abaAluno)
                .addContainerGap())
        );
        janelaAlunoLayout.setVerticalGroup(
            janelaAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, janelaAlunoLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(abaAluno, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoVoltar))
        );

        getContentPane().add(janelaAluno, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoVoltarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_botaoVoltarActionPerformed

    private void ButtonSalvarInserirAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSalvarInserirAlunoActionPerformed
       
         
        //SALVAR ALUNO
       // botaoVoltar.setText( campoCpfAluno.getText());
        //VERIICAR CPF
        //TENTAR SALVAR 
        
        
        Aluno aluno = new Aluno();
        aluno.setNome(campoNomeAluno.getText());
        String CPF = campoCpfAluno.getText();
        try{
            Long cpf = Long.parseLong(CPF);
            aluno.setCpf(cpf);
            if (aluno.validarCPF(aluno.getCpf())==false)
            {
              JOptionPane.showMessageDialog(null, "CPF Inválido!!!", "Atenção!!: " + "", JOptionPane.INFORMATION_MESSAGE);
            
            
            }
            
            else{
                         try{
                        AlunoDaoImpl alunodao = new AlunoDaoImpl();
                        alunodao.salvar(aluno);
            
            
            
                        }catch(Exception ex){
            
                       JOptionPane.showMessageDialog(null, "Aluno já existente!", "Atenção!!: " + "", JOptionPane.INFORMATION_MESSAGE);
                    
                    
                 }
           }
            
        }catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null, "Parametro invalido!", "Atenção!!: " + "", JOptionPane.INFORMATION_MESSAGE);
        }
        dispose();
        
        
    }//GEN-LAST:event_ButtonSalvarInserirAlunoActionPerformed

    private void ButtonSalvarEditarAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSalvarEditarAlunoActionPerformed
       //chamar atualizar
       /* alunoN.setNome("tiGOS");
        alunoN.setCpf(14638431784L);
        
        alunoA.setCpf(14638431780L);
        alunoA.setNome(alunoN.getNome()); okay
        ad.atualizar(alunoA, alunoN);
        */
        
        Aluno alunoN = new Aluno();
        Aluno alunoA = new Aluno();
        AlunoDaoImpl alunodao = new AlunoDaoImpl();
        
        alunoN.setNome(campoNomeAlunoN.getText());
        try{
            alunoA.setCpf(Long.parseLong(campoEditarCpfAluno.getText()));
            alunoA.setNome(alunoN.getNome());
            alunodao.atualizar(alunoA, alunoN);
            
            
        }catch(Exception ex){
            
            
             JOptionPane.showMessageDialog(null, "CPF Inválido!!!", "Atenção!!: " + "", JOptionPane.INFORMATION_MESSAGE);
            
        }
        
        
    }//GEN-LAST:event_ButtonSalvarEditarAlunoActionPerformed

    private void ButtonSalvarRemoverAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSalvarRemoverAlunoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonSalvarRemoverAlunoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FormAluno dialog = new FormAluno(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonSalvarEditarAluno;
    private javax.swing.JButton ButtonSalvarInserirAluno;
    private javax.swing.JButton ButtonSalvarRemoverAluno;
    private javax.swing.JTextField CampoRemoverCpfAluno;
    private javax.swing.JTabbedPane abaAluno;
    private javax.swing.JButton botaoVoltar;
    private javax.swing.JTextField campoCpfAluno;
    private javax.swing.JTextField campoEditarCpfAluno;
    private javax.swing.JTextField campoNomeAluno;
    private javax.swing.JTextField campoNomeAlunoN;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JPanel janelaAluno;
    private javax.swing.JLabel labelCPFAluno;
    private javax.swing.JLabel labelCpfAluno;
    private javax.swing.JLabel labelNomeAluno;
    private javax.swing.JLabel labelNomeAlunoN;
    private javax.swing.JLabel labelRemoverCpfAluno;
    private javax.swing.JTable tblObjetos;
    // End of variables declaration//GEN-END:variables
}
