/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import DAOsImpl.AtividadeDaoImpl;
import POJOs.Atividade;
import javax.swing.JOptionPane;

/**
 *
 * @author john
 */
public class FormAtividade extends javax.swing.JDialog {

    /**
     * Creates new form FormAtividade
     */
    public FormAtividade(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        janelaAtividade = new javax.swing.JPanel();
        botaoVoltar = new javax.swing.JButton();
        abaAtividade = new javax.swing.JTabbedPane();
        abaInserirAtividade = new javax.swing.JPanel();
        labelNomeAtividade = new javax.swing.JLabel();
        labelTipoAtividade = new javax.swing.JLabel();
        campoNomeAtividade = new javax.swing.JTextField();
        campoTipoAtividade = new javax.swing.JTextField();
        labelDataAtividade = new javax.swing.JLabel();
        campoDataAtividade = new javax.swing.JTextField();
        labelValorAtividade = new javax.swing.JLabel();
        campoValorAtividade = new javax.swing.JTextField();
        buttonSalvarInserirAtividade = new javax.swing.JButton();
        abaRemoverAtividade = new javax.swing.JPanel();
        labelRemoverNomeAtividade = new javax.swing.JLabel();
        CampoRemoverNomeAtividade = new javax.swing.JTextField();
        buttonSalvarRemoverAtividade = new javax.swing.JButton();
        abaInserirAtividadeTurma = new javax.swing.JPanel();
        labelCodTurma = new javax.swing.JLabel();
        campoCpfAluno1 = new javax.swing.JTextField();
        labelNomeAtividadeAluno1 = new javax.swing.JLabel();
        campoNomeAtividade1 = new javax.swing.JTextField();
        buttonSalvarInserirAlunoAtividade = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        janelaAtividade.setBorder(javax.swing.BorderFactory.createTitledBorder("Atividade"));
        janelaAtividade.setToolTipText("");

        botaoVoltar.setText("Voltar");
        botaoVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVoltarActionPerformed(evt);
            }
        });

        labelNomeAtividade.setText("Nome da Atividade: ");

        labelTipoAtividade.setText("Tipo:");

        labelDataAtividade.setText("Data da Atividade:");

        labelValorAtividade.setText("Valor da Atividade:");

        buttonSalvarInserirAtividade.setText("Salvar");
        buttonSalvarInserirAtividade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSalvarInserirAtividadeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout abaInserirAtividadeLayout = new javax.swing.GroupLayout(abaInserirAtividade);
        abaInserirAtividade.setLayout(abaInserirAtividadeLayout);
        abaInserirAtividadeLayout.setHorizontalGroup(
            abaInserirAtividadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abaInserirAtividadeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(abaInserirAtividadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelTipoAtividade)
                    .addComponent(labelNomeAtividade)
                    .addComponent(labelDataAtividade))
                .addGap(4, 4, 4)
                .addGroup(abaInserirAtividadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(abaInserirAtividadeLayout.createSequentialGroup()
                        .addComponent(campoDataAtividade, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(labelValorAtividade)
                        .addGap(6, 6, 6)
                        .addComponent(campoValorAtividade, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(campoTipoAtividade)
                    .addComponent(campoNomeAtividade))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(buttonSalvarInserirAtividade))
        );
        abaInserirAtividadeLayout.setVerticalGroup(
            abaInserirAtividadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abaInserirAtividadeLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(abaInserirAtividadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNomeAtividade)
                    .addComponent(campoNomeAtividade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(abaInserirAtividadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTipoAtividade)
                    .addComponent(campoTipoAtividade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(abaInserirAtividadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDataAtividade)
                    .addComponent(campoDataAtividade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelValorAtividade)
                    .addComponent(campoValorAtividade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, abaInserirAtividadeLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(buttonSalvarInserirAtividade))
        );

        abaAtividade.addTab("Inserir", abaInserirAtividade);

        labelRemoverNomeAtividade.setText("Nome da Atividade:");

        buttonSalvarRemoverAtividade.setText("Salvar");

        javax.swing.GroupLayout abaRemoverAtividadeLayout = new javax.swing.GroupLayout(abaRemoverAtividade);
        abaRemoverAtividade.setLayout(abaRemoverAtividadeLayout);
        abaRemoverAtividadeLayout.setHorizontalGroup(
            abaRemoverAtividadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abaRemoverAtividadeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelRemoverNomeAtividade)
                .addGap(18, 18, 18)
                .addComponent(CampoRemoverNomeAtividade, javax.swing.GroupLayout.DEFAULT_SIZE, 387, Short.MAX_VALUE)
                .addGap(26, 26, 26))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, abaRemoverAtividadeLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(buttonSalvarRemoverAtividade))
        );
        abaRemoverAtividadeLayout.setVerticalGroup(
            abaRemoverAtividadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abaRemoverAtividadeLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(abaRemoverAtividadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelRemoverNomeAtividade)
                    .addComponent(CampoRemoverNomeAtividade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addComponent(buttonSalvarRemoverAtividade))
        );

        abaAtividade.addTab("Remover", abaRemoverAtividade);

        labelCodTurma.setText("Código da Turma:");

        labelNomeAtividadeAluno1.setText("Nome da Atividade:");

        buttonSalvarInserirAlunoAtividade.setText("Salvar");

        javax.swing.GroupLayout abaInserirAtividadeTurmaLayout = new javax.swing.GroupLayout(abaInserirAtividadeTurma);
        abaInserirAtividadeTurma.setLayout(abaInserirAtividadeTurmaLayout);
        abaInserirAtividadeTurmaLayout.setHorizontalGroup(
            abaInserirAtividadeTurmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abaInserirAtividadeTurmaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(abaInserirAtividadeTurmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelCodTurma)
                    .addComponent(labelNomeAtividadeAluno1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                .addGroup(abaInserirAtividadeTurmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(campoNomeAtividade1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoCpfAluno1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, abaInserirAtividadeTurmaLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(buttonSalvarInserirAlunoAtividade))
        );
        abaInserirAtividadeTurmaLayout.setVerticalGroup(
            abaInserirAtividadeTurmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abaInserirAtividadeTurmaLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(abaInserirAtividadeTurmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCodTurma)
                    .addComponent(campoCpfAluno1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(abaInserirAtividadeTurmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNomeAtividadeAluno1)
                    .addComponent(campoNomeAtividade1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(buttonSalvarInserirAlunoAtividade))
        );

        abaAtividade.addTab("Inserir Aluno na Atividade", abaInserirAtividadeTurma);

        javax.swing.GroupLayout janelaAtividadeLayout = new javax.swing.GroupLayout(janelaAtividade);
        janelaAtividade.setLayout(janelaAtividadeLayout);
        janelaAtividadeLayout.setHorizontalGroup(
            janelaAtividadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, janelaAtividadeLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(botaoVoltar))
            .addGroup(janelaAtividadeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(abaAtividade)
                .addContainerGap())
        );
        janelaAtividadeLayout.setVerticalGroup(
            janelaAtividadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, janelaAtividadeLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(abaAtividade)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoVoltar))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(janelaAtividade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(janelaAtividade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(261, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoVoltarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_botaoVoltarActionPerformed

    private void buttonSalvarInserirAtividadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSalvarInserirAtividadeActionPerformed
       
        
        Atividade atividade = new Atividade();
        
        atividade.setNome(campoNomeAtividade.getText());
        atividade.setData(campoDataAtividade.getText());
        atividade.setTipo(campoTipoAtividade.getText());
        try{
            atividade.setValorAtividade(Double.parseDouble(campoValorAtividade.getText()));
            AtividadeDaoImpl atividadedao = new AtividadeDaoImpl();
            atividadedao.salvar(atividade);
            dispose();
            
        }catch(Exception ex)
        {
                JOptionPane.showMessageDialog(null, "Parametro invalido!", "Atenção!!: " + "", JOptionPane.INFORMATION_MESSAGE);
        }
       
       
        
        
    }//GEN-LAST:event_buttonSalvarInserirAtividadeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormAtividade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormAtividade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormAtividade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormAtividade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FormAtividade dialog = new FormAtividade(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CampoRemoverNomeAtividade;
    private javax.swing.JTabbedPane abaAtividade;
    private javax.swing.JPanel abaInserirAtividade;
    private javax.swing.JPanel abaInserirAtividadeTurma;
    private javax.swing.JPanel abaRemoverAtividade;
    private javax.swing.JButton botaoVoltar;
    private javax.swing.JButton buttonSalvarInserirAlunoAtividade;
    private javax.swing.JButton buttonSalvarInserirAtividade;
    private javax.swing.JButton buttonSalvarRemoverAtividade;
    private javax.swing.JTextField campoCpfAluno1;
    private javax.swing.JTextField campoDataAtividade;
    private javax.swing.JTextField campoNomeAtividade;
    private javax.swing.JTextField campoNomeAtividade1;
    private javax.swing.JTextField campoTipoAtividade;
    private javax.swing.JTextField campoValorAtividade;
    private javax.swing.JPanel janelaAtividade;
    private javax.swing.JLabel labelCodTurma;
    private javax.swing.JLabel labelDataAtividade;
    private javax.swing.JLabel labelNomeAtividade;
    private javax.swing.JLabel labelNomeAtividadeAluno1;
    private javax.swing.JLabel labelRemoverNomeAtividade;
    private javax.swing.JLabel labelTipoAtividade;
    private javax.swing.JLabel labelValorAtividade;
    // End of variables declaration//GEN-END:variables
}
