/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

/**
 *
 * @author john
 */
public class FormAtividade extends javax.swing.JDialog {

    /**
     * Creates new form FormAtividade
     */
    public FormAtividade(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        janelaAtividade = new javax.swing.JPanel();
        buttonSalvarAtividade = new javax.swing.JButton();
        botaoVoltar = new javax.swing.JButton();
        abaAtividade = new javax.swing.JTabbedPane();
        abaInserirAtividade = new javax.swing.JPanel();
        labelNomeAtividade = new javax.swing.JLabel();
        labelTipoAtividade = new javax.swing.JLabel();
        campoNomeDisciplina = new javax.swing.JTextField();
        campoEmentaDisciplina = new javax.swing.JTextField();
        labelDataAtividade = new javax.swing.JLabel();
        campoCargaDisciplina = new javax.swing.JTextField();
        labelValorAtividade = new javax.swing.JLabel();
        campoValorAtividade = new javax.swing.JTextField();
        abaRemoverAtividade = new javax.swing.JPanel();
        labelRemoverNomeAtividade = new javax.swing.JLabel();
        CampoRemoverNomeAtividade = new javax.swing.JTextField();
        abaInserirAlunoAtividade = new javax.swing.JPanel();
        labelCpfAluno = new javax.swing.JLabel();
        campoCpfAluno = new javax.swing.JTextField();
        labelNomeAtividadeAluno = new javax.swing.JLabel();
        campoNomeAtividade = new javax.swing.JTextField();
        abaRemoverAlunoAtividade1 = new javax.swing.JPanel();
        labelCpfAluno1 = new javax.swing.JLabel();
        campoCpfAluno1 = new javax.swing.JTextField();
        labelNomeAtividadeAluno1 = new javax.swing.JLabel();
        campoNomeAtividade1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        janelaAtividade.setBorder(javax.swing.BorderFactory.createTitledBorder("Atividade"));
        janelaAtividade.setToolTipText("");

        buttonSalvarAtividade.setText("Salvar");

        botaoVoltar.setText("Voltar");
        botaoVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVoltarActionPerformed(evt);
            }
        });

        labelNomeAtividade.setText("Nome da Atividade: ");

        labelTipoAtividade.setText("Tipo:");

        labelDataAtividade.setText("Data da Atividade:");

        labelValorAtividade.setText("Valor da Atividade:");

        javax.swing.GroupLayout abaInserirAtividadeLayout = new javax.swing.GroupLayout(abaInserirAtividade);
        abaInserirAtividade.setLayout(abaInserirAtividadeLayout);
        abaInserirAtividadeLayout.setHorizontalGroup(
            abaInserirAtividadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abaInserirAtividadeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(abaInserirAtividadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelTipoAtividade)
                    .addComponent(labelNomeAtividade)
                    .addComponent(labelDataAtividade))
                .addGap(4, 4, 4)
                .addGroup(abaInserirAtividadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(abaInserirAtividadeLayout.createSequentialGroup()
                        .addComponent(campoCargaDisciplina, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(labelValorAtividade)
                        .addGap(6, 6, 6)
                        .addComponent(campoValorAtividade, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(campoEmentaDisciplina)
                    .addComponent(campoNomeDisciplina))
                .addContainerGap(75, Short.MAX_VALUE))
        );
        abaInserirAtividadeLayout.setVerticalGroup(
            abaInserirAtividadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abaInserirAtividadeLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(abaInserirAtividadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNomeAtividade)
                    .addComponent(campoNomeDisciplina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(abaInserirAtividadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTipoAtividade)
                    .addComponent(campoEmentaDisciplina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(abaInserirAtividadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDataAtividade)
                    .addComponent(campoCargaDisciplina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelValorAtividade)
                    .addComponent(campoValorAtividade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        abaAtividade.addTab("Inserir", abaInserirAtividade);

        labelRemoverNomeAtividade.setText("Nome da Atividade:");

        javax.swing.GroupLayout abaRemoverAtividadeLayout = new javax.swing.GroupLayout(abaRemoverAtividade);
        abaRemoverAtividade.setLayout(abaRemoverAtividadeLayout);
        abaRemoverAtividadeLayout.setHorizontalGroup(
            abaRemoverAtividadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abaRemoverAtividadeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelRemoverNomeAtividade)
                .addGap(18, 18, 18)
                .addComponent(CampoRemoverNomeAtividade, javax.swing.GroupLayout.DEFAULT_SIZE, 387, Short.MAX_VALUE)
                .addGap(26, 26, 26))
        );
        abaRemoverAtividadeLayout.setVerticalGroup(
            abaRemoverAtividadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abaRemoverAtividadeLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(abaRemoverAtividadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelRemoverNomeAtividade)
                    .addComponent(CampoRemoverNomeAtividade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(101, Short.MAX_VALUE))
        );

        abaAtividade.addTab("Remover", abaRemoverAtividade);

        labelCpfAluno.setText("CPF do Aluno:");

        labelNomeAtividadeAluno.setText("Nome da Atividade:");

        javax.swing.GroupLayout abaInserirAlunoAtividadeLayout = new javax.swing.GroupLayout(abaInserirAlunoAtividade);
        abaInserirAlunoAtividade.setLayout(abaInserirAlunoAtividadeLayout);
        abaInserirAlunoAtividadeLayout.setHorizontalGroup(
            abaInserirAlunoAtividadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abaInserirAlunoAtividadeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(abaInserirAlunoAtividadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelCpfAluno)
                    .addComponent(labelNomeAtividadeAluno))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                .addGroup(abaInserirAlunoAtividadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(campoNomeAtividade, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoCpfAluno, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        abaInserirAlunoAtividadeLayout.setVerticalGroup(
            abaInserirAlunoAtividadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abaInserirAlunoAtividadeLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(abaInserirAlunoAtividadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCpfAluno)
                    .addComponent(campoCpfAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(abaInserirAlunoAtividadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNomeAtividadeAluno)
                    .addComponent(campoNomeAtividade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(59, Short.MAX_VALUE))
        );

        abaAtividade.addTab("Inserir Aluno na Atividade", abaInserirAlunoAtividade);

        labelCpfAluno1.setText("CPF do Aluno:");

        labelNomeAtividadeAluno1.setText("Nome da Atividade:");

        javax.swing.GroupLayout abaRemoverAlunoAtividade1Layout = new javax.swing.GroupLayout(abaRemoverAlunoAtividade1);
        abaRemoverAlunoAtividade1.setLayout(abaRemoverAlunoAtividade1Layout);
        abaRemoverAlunoAtividade1Layout.setHorizontalGroup(
            abaRemoverAlunoAtividade1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abaRemoverAlunoAtividade1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(abaRemoverAlunoAtividade1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelCpfAluno1)
                    .addComponent(labelNomeAtividadeAluno1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                .addGroup(abaRemoverAlunoAtividade1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(campoNomeAtividade1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoCpfAluno1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        abaRemoverAlunoAtividade1Layout.setVerticalGroup(
            abaRemoverAlunoAtividade1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abaRemoverAlunoAtividade1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(abaRemoverAlunoAtividade1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCpfAluno1)
                    .addComponent(campoCpfAluno1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(abaRemoverAlunoAtividade1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNomeAtividadeAluno1)
                    .addComponent(campoNomeAtividade1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(59, Short.MAX_VALUE))
        );

        abaAtividade.addTab("Inserir Aluno na Atividade", abaRemoverAlunoAtividade1);

        javax.swing.GroupLayout janelaAtividadeLayout = new javax.swing.GroupLayout(janelaAtividade);
        janelaAtividade.setLayout(janelaAtividadeLayout);
        janelaAtividadeLayout.setHorizontalGroup(
            janelaAtividadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, janelaAtividadeLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(buttonSalvarAtividade)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoVoltar))
            .addGroup(janelaAtividadeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(abaAtividade)
                .addContainerGap())
        );
        janelaAtividadeLayout.setVerticalGroup(
            janelaAtividadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, janelaAtividadeLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(abaAtividade)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(janelaAtividadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoVoltar)
                    .addComponent(buttonSalvarAtividade)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(janelaAtividade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(janelaAtividade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(261, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoVoltarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_botaoVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormAtividade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormAtividade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormAtividade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormAtividade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FormAtividade dialog = new FormAtividade(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CampoRemoverNomeAtividade;
    private javax.swing.JTabbedPane abaAtividade;
    private javax.swing.JPanel abaInserirAlunoAtividade;
    private javax.swing.JPanel abaInserirAtividade;
    private javax.swing.JPanel abaRemoverAlunoAtividade1;
    private javax.swing.JPanel abaRemoverAtividade;
    private javax.swing.JButton botaoVoltar;
    private javax.swing.JButton buttonSalvarAtividade;
    private javax.swing.JTextField campoCargaDisciplina;
    private javax.swing.JTextField campoCpfAluno;
    private javax.swing.JTextField campoCpfAluno1;
    private javax.swing.JTextField campoEmentaDisciplina;
    private javax.swing.JTextField campoNomeAtividade;
    private javax.swing.JTextField campoNomeAtividade1;
    private javax.swing.JTextField campoNomeDisciplina;
    private javax.swing.JTextField campoValorAtividade;
    private javax.swing.JPanel janelaAtividade;
    private javax.swing.JLabel labelCpfAluno;
    private javax.swing.JLabel labelCpfAluno1;
    private javax.swing.JLabel labelDataAtividade;
    private javax.swing.JLabel labelNomeAtividade;
    private javax.swing.JLabel labelNomeAtividadeAluno;
    private javax.swing.JLabel labelNomeAtividadeAluno1;
    private javax.swing.JLabel labelRemoverNomeAtividade;
    private javax.swing.JLabel labelTipoAtividade;
    private javax.swing.JLabel labelValorAtividade;
    // End of variables declaration//GEN-END:variables
}
